# Generated by Django 5.2.3 on 2025-06-11 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dateofbirth',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
